# Generated by Django 4.0.6 on 2022-07-21 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=400)),
                ('esp_resume', models.CharField(default='None', max_length=2000)),
                ('eng_resume', models.CharField(default='None', max_length=2000)),
                ('val_resume', models.CharField(default='None', max_length=2000)),
                ('duration', models.FloatField(default='None', max_length=200)),
                ('dificulty', models.CharField(default='None', max_length=200)),
                ('start', models.CharField(default='None', max_length=200)),
                ('end_point', models.CharField(default='None', max_length=200)),
                ('image', models.CharField(default='None', max_length=200)),
                ('url', models.CharField(default='None', max_length=200)),
                ('transport', models.CharField(default='None', max_length=200)),
                ('type', models.CharField(default='None', max_length=200)),
                ('esp_description', models.CharField(default='None', max_length=4500)),
                ('val_description', models.CharField(default='None', max_length=4500)),
                ('eng_description', models.CharField(default='None', max_length=4500)),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='None', max_length=200)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('val_description', models.CharField(default='None', max_length=4500)),
                ('cast_description', models.CharField(default='None', max_length=4500)),
                ('eng_description', models.CharField(default='None', max_length=7000)),
                ('images', models.CharField(default='None', max_length=200)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.rutas')),
            ],
        ),
    ]
