# Generated by Django 4.0.6 on 2022-07-21 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_alter_poi_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='images',
            field=models.CharField(default='None', max_length=2500),
        ),
    ]
