# Generated by Django 4.0.6 on 2022-07-26 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='type',
            new_name='route_type',
        ),
    ]
